### ISSUE TITLE
Packages errors

### ISSUE THREAD

**Issue by Adafede** [sdrogers/vimms#2]
Hi, 

I wanted to try your tool but went blocked quite fast. I followed all the instructions and it seems that at least the clr package is missing from the pipenv created by default. I tried installing it by myself in the directory but this led to this error: 

ImportError: cannot import name 'ListAssemblies' from 'clr' (/Users/rutza/.local/share/virtualenvs/vimms-nE9rFAA8/lib/python3.7/site-packages/clr/__init__.py)

Any suggestion?

Thanks a lot in advance

**Comment by joewandy** [comment]
Hi @Adafede, thank you for finding the bug. The clr package is not needed unless you want to run the simulator framework on top of an actual Thermo Fusion instrument (which is the next stage of our project). I've fixed the problem in the commit above, and also updated the example notebooks we have so they run. Could you please do a pull on the latest commit please?

Also for some quick examples on how to get started using the simulator, you can check out our test cases: https://github.com/sdrogers/vimms/blob/master/run_tests.sh.

**Comment by Adafede** [comment]
@joewandy 

Hi, thanks a lot for the quick fix! I pulled the new version and it went fine. I'm going through the procedure described in the readme to try to understand your manuscript set and reproduce it. Taking some time and memory! Afterwards, I'll try on mine :)

Thanks a lot again
