### ISSUE TITLE
defaultInstrumentConfigurationRef attribute not included in mzML output

### ISSUE THREAD

**Issue by RonanDaly** [sdrogers/vimms#228]
When trying to run BatMass, it complains about a missing attribute in a run tag
```
umich.ms.fileio.exceptions.RunHeaderParsingException: Could not find "defaultInstrumentConfigurationRef" attribute of <run> tag, it is required by mzML standard
```
We can see this in the [mzML standard](https://raw.githubusercontent.com/HUPO-PSI/mzML/master/schema/schema_1.1/mzML1.1.0.xsd)

**Comment by joewandy** [comment]
Probably no longer needed
