### ISSUE TITLE
[WIP] JOSS Review (@MKoesters)

### ISSUE THREAD

**Issue by MKoesters** [sdrogers/vimms#234]
## Review checklist for @MKoesters
✨ Important: Please do not use the _Convert to issue_ functionality when working through this checklist, instead, please open any new issues associated with your review <a target="_blank" href="https://github.com/glasgowcompbio/vimms/">in the software repository associated with the submission</a>. ✨

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/glasgowcompbio/vimms/">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@joewandy) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

Reviewers comments
=================

Major: None

Minor: 
- Contributing guidelines are available, but not properly linked in the documentation or README
- notebooks in `examples/01.\ vimms\ \(Wandy\ et\ al\ 2019\)/` dont seem to work
 ```
from vimms.DataGenerator import extract_hmdb_metabolite, get_data_source, get_spectral_feature_database
from vimms.MassSpec import IndependentMassSpectrometer
from vimms.Controller import SimpleMs1Controller
from vimms.Common import *
from vimms.Roi import make_roi, RoiToChemicalCreator
from vimms.FeatureExtraction import extract_roi

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Input In [5], in <module>
----> 1 from vimms.DataGenerator import extract_hmdb_metabolite, get_data_source, get_spectral_feature_database
      2 from vimms.MassSpec import IndependentMassSpectrometer
      3 from vimms.Controller import SimpleMs1Controller

ModuleNotFoundError: No module named 'vimms.DataGenerator'
```

Same with `02.\ DDA\ Strategies\ \(Davies\ et\ al\ 2020\)/01.\ Model\ Optimisation.ipynb`
I started jupyer in the notebooks and in the root folder, after running `pipenv install && pipenv shell`
```
from vimms.PythonMzmine import *
from vimms.MassSpec import IndependentMassSpectrometer
from vimms.Controller import TopNController,WeightedDEWController
from vimms.PythonMzmine import *

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Input In [4], in <module>
----> 1 from vimms.PythonMzmine import *
      2 from vimms.MassSpec import IndependentMassSpectrometer
      3 from vimms.Controller import TopNController,WeightedDEWController

ModuleNotFoundError: No module named 'vimms.PythonMzmine'
```

- Regarding above: `from xxx import *` is considered bad practice (at least imo,  see [here](https://www.geeksforgeeks.org/why-import-star-in-python-is-a-bad-idea/))

**Comment by joewandy** [comment]
Dear Manuel (@MKoesters), 

Thank you for your review. We're glad that you found no major problem with ViMMS. In the master branch, we have addressed the minor issues that you found. Here's an itemised list of the minor issues and our comments:

> 1. Contributing guidelines are available, but not properly linked in the documentation or README

We have included a Contributing guideline [here](https://github.com/glasgowcompbio/vimms/blob/master/CONTRIBUTING.md), and made sure that it's now linked from the README.

> 2. example notebooks are not working

Those notebooks were broken since the project is still in active development, and we forgot to update the notebooks. We've gone through all notebooks in the [examples](https://github.com/glasgowcompbio/vimms/tree/master/examples) and [demo](https://github.com/glasgowcompbio/vimms/tree/master/demo) folder and make sure they now run.

> 3. Usage of `import *` 

We agree that it's generally a bad practice to use `import *`, so we've made sure to eliminate them from the codebase and from the notebooks as well.

I hope these changes are satisfactory to address the minor issues above. If there's any other problem, please let me know.

Thank you,

Joe Wandy (on behalf of the ViMMS team)

**Comment by MKoesters** [comment]
Closing this since all minors are resolved!
