### ISSUE TITLE
Processing Times Have Extreme Outliers

### ISSUE THREAD

**Issue by mcbrider5002** [sdrogers/vimms#240]
For performance-measuring purposes, we collect processing times in the base controller (which is inherited by most classes).  Most scans are observably <0.2 seconds. However, in rare cases the scan time spikes to >1 second. We need to find the cause of this and correct it.

**Comment by joewandy** [comment]
Can this be closed @mcbrider5002 ?

**Comment by mcbrider5002** [comment]
@joewandy I believe you said you would look into this at some point but I'm not sure you ever did?

**Comment by joewandy** [comment]
Let's close it for now until it becomes a problem
